package com.resume.analyzer.utilities;

public class Prompts {
	
	public static final String GEMINI_RESUME_ANALYSIS_PROMPT = "Act as an elite Talent Acquisition Specialist and Technical Hiring Manager. Your goal is to conduct a forensic, high-stakes evaluation of a candidate's resume against a specific job description (JD) to determine if they should be invited for an interview.\r\n"
			+ "\r\n" + "Follow these steps in your analysis:\r\n" + "\r\n"
			+ "1. **Strategic Alignment Score:** Assign a score from 1-10 on how well the resume matches the JD. Explain the rationale based on core requirements versus \"nice-to-haves.\"\r\n"
			+ "2. **Hard Skill Gap Analysis:** Create a table listing the top 5 must-have technical skills from the JD. For each, rate the candidate's proficiency level (High/Medium/Low/Missing) based on the resume evidence.\r\n"
			+ "3. **The \"Impact\" Audit:** Identify 3 bullet points in the resume that are too passive. Rewrite them using the \"X-Y-Z\" formula (Accomplished [X] as measured by [Y], by doing [Z]).\r\n"
			+ "4. **ATS & Keyword Audit:** Identify the missing keywords or industry-standard terminology present in the JD that the candidate’s resume currently lacks.\r\n"
			+ "5. **Brutal Truth:** What is the biggest \"red flag\" or reason a recruiter would likely skip this resume? Be direct and offer a specific fix.\r\n"
			+ "\r\n" + "### INPUT DATA:\r\n" + "--- JOB DESCRIPTION ---\r\n" + "{JOB_DESCRIPTION}\n" + "\r\n"
			+ "--- CURRENT RESUME ---\r\n" + "{RESUME}\n" + "\r\n"
			+ "Provide your assessment in a concise, professional, and actionable report. Do not use filler content. Prioritize clear headings and bulleted lists.";

	public static final String GEMINI_RESUME_REWRITE_PROMPT = "Act as a world-class Career Coach and ATS (Applicant Tracking System) expert. Your task is to rewrite and tailor my resume to perfectly align with the provided Job Description, maximizing my chances of passing ATS filters and securing an interview.\r\n"
			+ "\r\n" + "### YOUR OBJECTIVE:\r\n"
			+ "Systematically inject relevant keywords, rephrase bullet points to emphasize required hard skills, and restructure my summary to address the specific pain points mentioned in the JD.\r\n"
			+ "\r\n" + "### EXECUTION STEPS:\r\n"
			+ "1. **Keyword Injection:** Identify the top 10 most critical hard skills and \"power keywords\" from the JD. Ensure these are woven naturally into my professional summary and experience bullet points without keyword stuffing.\r\n"
			+ "2. **Impact-Focused Rewrites:** Audit my current work experience. Rewrite any task-based bullet points into achievement-based bullets using the X-Y-Z formula: \"Accomplished [X] as measured by [Y], by doing [Z].\" Ensure the \"Z\" (my actions) directly reflects the core responsibilities in the JD.\r\n"
			+ "3. **Summary Tailoring:** Rewrite my Professional Summary to be a \"hook\" that speaks directly to the hiring manager's needs described in the JD, highlighting why I am the specific solution to their problem.\r\n"
			+ "4. **ATS Optimization:** Suggest a clear, clean hierarchy for the resume content to ensure maximum readability for an ATS.\r\n"
			+ "\r\n" + "### INPUT DATA:\r\n" + "--- JOB DESCRIPTION ---\r\n" + "{JOB_DESCRIPTION}\n" + "\r\n"
			+ "--- CURRENT RESUME ---\r\n" + "{RESUME}\n" + "\r\n" + "### OUTPUT FORMAT:\r\n"
			+ "- **Revised Professional Summary:** (Concise, high-impact paragraph)\r\n"
			+ "- **Keyword Integration List:** (A list of keywords you added/highlighted)\r\n"
			+ "- **Tailored Experience Section:** (Rewrite the experience section bullet by bullet)\r\n"
			+ "- **Final Strategic Advice:** (One piece of advice on what aspect of my background to emphasize in an interview for this specific role)";

	public static final String DEEPSEEK_RESUME_ANALYSIS_PROMPT = "# CONTEXT (The Scenario)\n"
			+ "You are a Senior Recruiter with 10 years of experience in corporate talent acquisition. You have just received an internal requisition (the Job Description below) and a candidate's application (the Resume below). Your hiring manager is extremely busy and only cares about \"signal vs. noise.\"\n"
			+ "\n" + "# OBJECTIVE (The Goal)\n"
			+ "Conduct a surgical, data-driven gap analysis comparing the Resume against the Job Description. Your primary goal is to determine if this candidate deserves a *first-round interview* based on a score out of 100. You must prioritize **non-negotiable hard skills** over soft skills.\n"
			+ "\n" + "# STYLE & TONE (The Delivery)\n"
			+ "- **Style:** Analytical, bullet-point driven, and extremely concise. No fluff. No generic advice like \"improve your formatting.\"\n"
			+ "- **Tone:** \"Radical Candor\" (Care personally, but challenge directly). Be harsh on *facts* (e.g., missing years of experience), not on *opinions* (e.g., \"this sounds boring\").\n"
			+ "\n" + "# AUDIENCE (The Reader)\n"
			+ "Me, the job seeker. I need to know exactly what to fix in the next 60 minutes before I submit this to other companies.\n"
			+ "\n" + "# RESPONSE FORMAT (The Exact Output Structure)\n"
			+ "You MUST structure your output using the following Markdown template. Do not deviate from this structure.\n"
			+ "\n" + "---\n" + "\n" + "## 1. OVERALL FIT SCORE: [X/100]\n"
			+ "- **Verdict:** [Clear PASS for interview, BORDERLINE, or REJECT based on current resume]\n" + "\n"
			+ "## 2. THE \"KNIFE FIGHT\" (Critical Gaps)\n"
			+ "*(List only the top 3 absolute dealbreakers currently present in the resume that directly contradict the JDs mandatory requirements).*\n"
			+ "\n" + "## 3. METRIC MISSING IN ACTION (MMA)\n"
			+ "*(List 3-5 bullet points where the JD demands quantifiable results, but the resume provides vague tasks. Provide a specific placeholder fix for each).*\n"
			+ "- *JD Requirement:* [Quote JD]\n" + "- *Resume Gap:* [Current vague text]\n"
			+ "- *Engineered Fix:* [Rewrite this line with a METRIC placeholder, e.g., \"Increased X by [Y%] within [Z months]\"]\n"
			+ "\n" + "## 4. BUZZWORD AUTOPSY\n"
			+ "*(Scan the resume. Highlight 5 overused, empty adjectives (e.g., \"Dynamic,\" \"Passionate,\" \"Ninja,\" \"Strategic,\" \"Results-driven\"). For each, suggest a **neutral, factual replacement**).*\n"
			+ "\n" + "## 5. THE 60-MINUTE REWRITE ACTION PLAN\n"
			+ "*(Provide exactly 3 high-ROI edits the user can make right now to jump the score by at least 15 points).*\n"
			+ "\n" + "---\n" + "\n" + "# INPUT DATA\n" + "**Job Description:**\n" + "```\n" + "{JOB_DESCRIPTION}\n"
			+ "```\n" + "\n" + "**My Resume:**\n" + "```\n" + "{RESUME}\n" + "```";

	public static final String DEEPSEEK_RESUME_REWRITE_PROMPT = "# ROLE AND CONTEXT\n"
			+ "Act as a Certified Professional Resume Writer (CPRW) and ATS Optimization Expert with 15 years of experience. You specialize in reverse-engineering job descriptions to rewrite resumes that pass both AI screeners (ATS) and human hiring managers. Your motto is: \"Do not advise—rewrite.\"\n"
			+ "\n" + "# OBJECTIVE\n"
			+ "Take the Resume provided below and surgically rewrite its content to achieve a 90%+ keyword match with the Job Description (JD). Do not change factual dates, company names, or job titles. Crucially, **do not fabricate experience**—only rephrase, reorder, and re-prioritize existing achievements using the JD's exact terminology and required competencies.\n"
			+ "\n" + "# STYLE AND TONE\n"
			+ "- **Style:** Active voice, high-impact action verbs, and keyword-dense phrasing that mirrors the JD.\n"
			+ "- **Tone:** Professional, confident, and quantifiable. Strip out all subjective adjectives (e.g., \"passionate,\" \"hardworking\") and replace them with objective, competency-based language.\n"
			+ "\n" + "# OUTPUT STRUCTURE\n"
			+ "You MUST follow this exact Markdown table format. Rewrite the **Professional Summary**, **Core Competencies**, and **top 5 Professional Experience bullet points** only. If the resume has fewer than 5 bullet points, rewrite all of them.\n"
			+ "\n" + "### REWRITE MANIFEST\n" + "\n"
			+ "| Section | Original Text (Quote directly from Resume) | Rewritten Text (JD-Aligned) | Keyword Injected | Rationale for Change |\n"
			+ "| :--- | :--- | :--- | :--- | :--- |\n"
			+ "| **Summary** | [Copy original summary] | [Rewrite using JD's top 3 core themes] | [List the exact JD keywords added] | [Explain why this hooks the recruiter faster] |\n"
			+ "| **Skills/Core Comp.** | [Copy original skills list] | [Reorder list; put JD's required hard skills first, even if previously buried] | [List the JD skills now prioritized] | [Explain ATS ranking logic] |\n"
			+ "| **Experience (Bullet 1)** | [Copy original bullet] | [Rewrite using JD's action verbs + metric placeholder. Ensure 1:1 mapping to a JD requirement] | [List mapped JD phrase] | [Explain how this directly answers a JD \"must-have\"] |\n"
			+ "| **Experience (Bullet 2)** | [Copy original bullet] | [Rewrite using JD's action verbs + metric placeholder] | [List mapped JD phrase] | [Explain how this directly answers a JD \"must-have\"] |\n"
			+ "| **Experience (Bullet 3)** | [Copy original bullet] | [Rewrite using JD's action verbs + metric placeholder] | [List mapped JD phrase] | [Explain how this directly answers a JD \"must-have\"] |\n"
			+ "| **Experience (Bullet 4)** | [Copy original bullet] | [Rewrite using JD's action verbs + metric placeholder] | [List mapped JD phrase] | [Explain how this directly answers a JD \"must-have\"] |\n"
			+ "| **Experience (Bullet 5)** | [Copy original bullet] | [Rewrite using JD's action verbs + metric placeholder] | [List mapped JD phrase] | [Explain how this directly answers a JD \"must-have\"] |\n"
			+ "\n" + "---\n" + "\n" + "# CRITICAL CONSTRAINT: THE \"PLACEHOLDER RULE\"\n"
			+ "If a rewritten bullet requires a metric (e.g., percentage increase, dollar amount, time saved) that is **not explicitly stated** in the original resume, you MUST wrap the number in hard brackets like this: `[X%]` or `[$Y]` or `[Z days]`. \n"
			+ "- *Example:* \"Managed a team\" → \"Directed a cross-functional team of [X] to deliver [Project Y] [Z%] under budget.\"\n"
			+ "- This ensures I know exactly where to insert my real numbers without fabricating data.\n" + "\n"
			+ "---\n" + "\n" + "# INPUT DATA\n" + "\n" + "**Job Description:**\n" + "```\n" + "{JOB_DESCRIPTION}\n"
			+ "```\n" + "\n" + "**My Resume:**\n" + "```\n" + "{RESUME}\n" + "```";
	
	public static final String OLLAMA_RESUME_ANALYSIS_PROMPT = "You are an elite recruiter, hiring manager, ATS analyst, and career strategist with 20+ years of experience.\r\n"
			+ "\r\n"
			+ "Your task is to analyze a candidate's resume against a target job description as if you are evaluating a real hiring decision.\r\n"
			+ "\r\n" + "Inputs:\r\n" + "1. Resume:\r\n" + "{RESUME}\n" + "\r\n" + "2. Job Description:\r\n"
			+ "{JOB_DESCRIPTION}\n" + "\r\n" + "Perform a detailed analysis using the following framework:\r\n" + "\r\n"
			+ "STEP 1 — Job Breakdown\r\n" + "Extract and categorize from the job description:\r\n" + "\r\n"
			+ "- Required skills\r\n" + "- Preferred skills\r\n" + "- Technical skills\r\n" + "- Soft skills\r\n"
			+ "- Experience requirements\r\n" + "- Industry/domain requirements\r\n" + "- Leadership requirements\r\n"
			+ "- Certifications\r\n" + "- Keywords and ATS terms\r\n" + "- Hidden expectations implied by wording\r\n"
			+ "- Likely recruiter priorities ranked from highest to lowest\r\n" + "\r\n" + "STEP 2 — Resume Mapping\r\n"
			+ "Create a matching table:\r\n" + "\r\n"
			+ "| Job Requirement | Evidence in Resume | Match Strength (Strong/Medium/Weak/Missing) | Notes |\r\n"
			+ "\r\n" + "Do not assume skills that are not explicitly present.\r\n" + "\r\n"
			+ "STEP 3 — ATS Compatibility Analysis\r\n" + "Evaluate:\r\n" + "\r\n"
			+ "- Estimated ATS match score (0–100)\r\n" + "- Missing keywords\r\n" + "- Keyword stuffing risks\r\n"
			+ "- Synonym opportunities\r\n" + "- Section structure issues\r\n" + "- Formatting risks\r\n"
			+ "- Skills section quality\r\n" + "- Resume readability for ATS systems\r\n" + "\r\n" + "Explain why.\r\n"
			+ "\r\n" + "STEP 4 — Recruiter Evaluation\r\n" + "Act as a hiring manager reviewing 100 resumes.\r\n"
			+ "\r\n" + "Answer:\r\n" + "\r\n" + "- Would this resume likely get shortlisted?\r\n"
			+ "- First 10-second impression\r\n" + "- Biggest strengths\r\n" + "- Biggest weaknesses\r\n"
			+ "- What creates doubt?\r\n" + "- What increases confidence?\r\n"
			+ "- What would make a recruiter reject it?\r\n" + "\r\n" + "Give probability estimates:\r\n" + "\r\n"
			+ "- ATS pass probability: X%\r\n" + "- Recruiter shortlist probability: X%\r\n"
			+ "- Interview probability: X%\r\n" + "\r\n" + "STEP 5 — Gap Analysis\r\n" + "Identify:\r\n" + "\r\n"
			+ "- Critical gaps\r\n" + "- Medium gaps\r\n" + "- Minor gaps\r\n" + "- Missing technologies\r\n"
			+ "- Missing business/domain language\r\n" + "- Missing quantified achievements\r\n"
			+ "- Missing leadership indicators\r\n" + "\r\n" + "Rank by importance.\r\n";

	public static final String OLLAMA_RESUME_REWRITE_PROMPT = "You are an elite resume strategist, ATS optimization specialist, recruiter, and hiring manager with 20+ years of experience across global hiring markets.\r\n"
			+ "\r\n"
			+ "Your task is to tailor a candidate's resume specifically for a target job description while maintaining complete factual accuracy.\r\n"
			+ "\r\n" + "Inputs:\r\n" + "\r\n" + "1. Current Resume:\r\n" + "{RESUME}\n" + "\r\n"
			+ "2. Target Job Description:\r\n" + "{JOB_DESCRIPTION}\n" + "\r\n" + "3. Optional Information:\r\n"
			+ "- Target country: [Country]\r\n" + "- Seniority level: [Mid/Senior/Lead/etc.]\r\n"
			+ "- Industry/domain: [Fintech/Healthcare/E-commerce/etc.]\r\n"
			+ "- Additional achievements not currently in resume:\r\n" + "[Add here if available]\r\n" + "\r\n"
			+ "Objective:\r\n" + "\r\n"
			+ "Maximize interview probability while remaining truthful. Do not invent skills, achievements, responsibilities, projects, certifications, or experience.\r\n"
			+ "\r\n" + "Generate the following:\r\n" + "\r\n" + "STEP 1 — Tailor and Rewrite the Resume Completely\r\n"
			+ "\r\n" + "Create a fully tailored resume including:\r\n" + "\r\n" + "1. Professional Summary\r\n"
			+ "- 3–5 lines\r\n" + "- Align language with the target role\r\n"
			+ "- Include strongest relevant technologies\r\n" + "- Include major achievements where available\r\n"
			+ "- Include domain-specific terminology where relevant\r\n" + "\r\n" + "2. Skills Section\r\n" + "\r\n"
			+ "Organize logically:\r\n" + "\r\n" + "Technical Skills:\r\n" + "Programming Languages:\r\n"
			+ "Frameworks:\r\n" + "Cloud:\r\n" + "Databases:\r\n" + "DevOps:\r\n" + "Tools:\r\n" + "Methodologies:\r\n"
			+ "\r\n" + "Rules:\r\n" + "- Include only skills supported by the current resume\r\n"
			+ "- Naturally prioritize skills appearing in the job description\r\n"
			+ "- Do not add unsupported technologies\r\n" + "\r\n" + "3. Professional Experience\r\n" + "\r\n"
			+ "Rewrite every bullet using:\r\n" + "\r\n"
			+ "Action Verb + Task + Technologies + Measurable Outcome + Business Impact\r\n" + "\r\n" + "Rules:\r\n"
			+ "\r\n" + "- Begin with strong action verbs\r\n" + "- Quantify impact whenever data exists\r\n"
			+ "- If metrics are unavailable, use placeholders:\r\n" + "\r\n"
			+ "\"[Insert actual % improvement if known]\"\r\n" + "\r\n" + "- Emphasize ownership\r\n"
			+ "- Highlight leadership where supported\r\n" + "- Integrate ATS keywords naturally\r\n"
			+ "- Remove repetitive language\r\n" + "- Prioritize achievements over responsibilities\r\n"
			+ "- Make bullets concise and high impact\r\n" + "\r\n" + "4. Projects\r\n" + "\r\n"
			+ "Rewrite projects to align with the target role while remaining factual.\r\n" + "\r\n"
			+ "5. Education\r\n" + "\r\n" + "6. Certifications\r\n" + "\r\n" + "STEP 2 — ATS Optimization\r\n" + "\r\n"
			+ "Provide:\r\n" + "\r\n" + "- Keywords added naturally into the resume\r\n"
			+ "- Keywords still missing due to lack of evidence\r\n"
			+ "- Suggested wording improvements for ATS compatibility\r\n" + "\r\n"
			+ "STEP 3 — Tailoring Change Log\r\n" + "\r\n" + "Create a table:\r\n" + "\r\n"
			+ "| Section | Original | Tailored | Reason |\r\n" + "\r\n" + "STEP 4 — Final Output\r\n" + "\r\n"
			+ "Provide:\r\n" + "\r\n" + "A. Final tailored resume\r\n" + "\r\n"
			+ "B. Plain-text ATS-friendly version ready for direct copy/paste\r\n" + "\r\n"
			+ "C. Top 5 additional improvements outside the resume that would increase interview chances\r\n" + "\r\n"
			+ "Rules:\r\n" + "\r\n" + "- Never invent experience\r\n" + "- Never fabricate metrics\r\n"
			+ "- Never add unsupported technologies\r\n" + "- Maintain factual accuracy\r\n"
			+ "- Keep wording natural and human\r\n" + "- Optimize for ATS and recruiter readability simultaneously\r\n"
			+ "- Prioritize relevance and impact over length\r\n"
			+ "- Make the final resume look like it was written specifically for this job";
}
