spring.application.name=ResumeAnalyzer

server.port=8080
spring.ai.model.chat = ollama

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.ai.ollama.chat.model=steamdj/llama3.1-cpu-only

spring.ai.ollama.chat.options.num-ctx=65535

spring.ai.retry.max-attempts=1

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.5-flash


spring.ai.deepseek.api-key=YOUR_API_KEY
spring.ai.deepseek.chat.model=deepseek-v4-pro
